# Generated by Django 4.1.7 on 2023-03-14 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hireme_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todo",
            new_name="Jobtitle",
        ),
    ]
